#! /bin/sh

root=$HOME
dotfile_name=".dotfiles"
dotfiles="$root/$dotfile_name/"
refresh=1

stow_package() {
    pkg_loc=$dotfiles$1
    # Check if the package has been stowed
    for fname in $(ls -A $pkg_loc); do
        refresh=1
        for rtfname in $(ls -A $root); do
            if [[ "$fname" == "$rtfname" ]]; then
                refresh=0
            fi
        done
        break
    done

    if [[ $refresh -eq 0 ]]; then
        echo "Restowing $1..."
        stow -t $root -d $dotfile_name -R $1
    else
        echo "Stowing $1..."
        stow -t $root -d $dotfile_name -S $1
    fi
}


if ! hash stow; then
    pacman -Syu stow
fi

if [[ -d $dotfiles ]]; then
    if [[ $# -gt 0 ]]; then
        if [[ -d $dotfiles$1 ]]; then
            stow_package $1
        else
            echo "$1 is not a package in $dotfiles."
        fi
    else
        # Cycle through packages
        for pkg in $(ls -A $dotfiles); do
            if [[ "$pkg" != ".git" && "$pkg" != ".gitignore" ]]; then
                stow_package $pkg
            fi
        done
    echo "Done."
    fi
fi
