#! /usr/bin/bash

# fetch the active displays that are connected
if ! hash xrandr ; then
    echo "Xrandr is not installed. Is this machine using the X display manager?"
    return 1
fi

maybe_displays=$(xrandr | grep " connected " | cut -d ' ' -f1 | tr '\n' ' ')

# read the displays into an array
IFS=' ' read -r -a displays <<< "$maybe_displays"

if [[ ${#displays[@]} -eq 1 ]]; then
    echo "Only one display detected. No need for arrangement."
    exit 0
elif [[ ${#displays[@]} -gt 2 ]]; then
    # if we have more than two than delegate to the user for now
    # TODO: handle 3 displays with a laptop
    xrandr --output "${displays[0]}" --auto \
        --output "${displays[2]}" --auto --above "${displays[0]}" \
        --output "${displays[1]}" --auto --right-of "${displays[2]}"
    exit 0
fi

# TODO set default configuration via config settings instead of guessing
# Assume that the first display listed is the central one
xrandr --output "${displays[0]}" --below "${displays[1]}" --auto
